# Generated by Django 4.1 on 2022-09-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id_compra",
                    models.AutoField(
                        db_column="ID_Compra", primary_key=True, serialize=False
                    ),
                ),
                ("cantidad", models.IntegerField(db_column="Cantidad")),
                ("proveedor", models.CharField(max_length=50)),
                ("pagado", models.CharField(max_length=50)),
                ("fecha", models.DateTimeField(db_column="Fecha")),
            ],
            options={"db_table": "Compra", "managed": False,},
        ),
        migrations.CreateModel(
            name="Lider",
            fields=[
                (
                    "id_lider",
                    models.AutoField(
                        db_column="ID_Lider", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("primer_apellido", models.CharField(max_length=50)),
                ("segundo_apellido", models.CharField(max_length=50)),
                ("salario", models.IntegerField(db_column="Salario")),
                ("ciudad_residencia", models.CharField(max_length=50)),
                ("cargo", models.CharField(max_length=50)),
                ("clasificacion", models.FloatField(db_column="Clasificacion")),
                ("documento_identidad", models.CharField(max_length=50)),
                (
                    "fecha_nacimiento",
                    models.DateTimeField(db_column="Fecha_Nacimiento"),
                ),
            ],
            options={"db_table": "Lider", "managed": False,},
        ),
        migrations.CreateModel(
            name="Materialconstruccion",
            fields=[
                (
                    "id_materialconstruccion",
                    models.AutoField(
                        db_column="ID_MaterialConstruccion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_material", models.CharField(max_length=50)),
                ("importado", models.CharField(max_length=50)),
                ("precio_unidad", models.IntegerField(db_column="Precio_Unidad")),
            ],
            options={"db_table": "MaterialConstruccion", "managed": False,},
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id_proyecto",
                    models.AutoField(
                        db_column="ID_Proyecto", primary_key=True, serialize=False
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(db_column="Fecha_Inicio")),
                ("constructora", models.CharField(max_length=50)),
                ("numero_banos", models.FloatField(db_column="Numero_Banos")),
                (
                    "numero_habitaciones",
                    models.FloatField(db_column="Numero_Habitaciones"),
                ),
                ("banco_vinculado", models.CharField(max_length=50)),
                (
                    "porcentaje_cuota_inicial",
                    models.FloatField(db_column="Porcentaje_Cuota_Inicial"),
                ),
                ("ciudad", models.CharField(max_length=50)),
                ("clasificacion", models.CharField(max_length=50)),
                ("acabados", models.CharField(max_length=50)),
                ("serial", models.CharField(max_length=50)),
            ],
            options={"db_table": "Proyecto", "managed": False,},
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id_tipo",
                    models.AutoField(
                        db_column="ID_Tipo", primary_key=True, serialize=False
                    ),
                ),
                ("codigo_tipo", models.IntegerField(db_column="Codigo_Tipo")),
                ("area_max", models.IntegerField(db_column="Area_Max")),
                ("financiable", models.IntegerField(db_column="Financiable")),
                ("estrato", models.IntegerField(db_column="Estrato")),
            ],
            options={"db_table": "Tipo", "managed": False,},
        ),
    ]
